# Generated by Django 3.1.2 on 2020-10-25 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('substitute', models.ForeignKey(help_text='Substitute product', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='products.product')),
                ('substituted', models.ForeignKey(help_text='Product to be substituted', on_delete=django.db.models.deletion.CASCADE, related_name='substituties', to='products.product')),
            ],
            options={
                'db_table': 'Favorite',
            },
        ),
    ]
