# Generated by Django 3.1.2 on 2020-10-23 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20201022_1445'),
        ('favorites', '0002_favorite_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('substituted', 'substitute')},
        ),
    ]
