# Generated by Django 3.1.3 on 2020-11-28 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20201106_1458'),
        ('favorites', '0003_auto_20201127_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='substituted',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
