# Generated by Django 3.1.3 on 2020-11-29 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0004_auto_20201128_1612'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together=set(),
        ),
    ]
