# Generated by Django 3.1.2 on 2020-10-25 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(help_text='Category name', max_length=255, unique=True)),
            ],
            options={
                'db_table': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(help_text='Product barcode', max_length=200, unique=True)),
                ('product_name', models.CharField(help_text='Product name', max_length=500)),
                ('nutrition_grade', models.CharField(help_text='Nutritional score of the product', max_length=1)),
                ('url', models.URLField(help_text='hyperlink to Openfoodfacts product page', max_length=500)),
                ('product_image', models.URLField(help_text='hyperlink to Openfoodfacts product image', max_length=500)),
                ('nutrition_image', models.URLField(blank=True, help_text='hyperlink to Openfoodfacts nutrition data image', max_length=500, null=True)),
                ('category', models.ManyToManyField(related_name='products', to='products.Category')),
            ],
            options={
                'db_table': 'Product',
            },
        ),
    ]
